# A.2 Extensión de ecosistemas naturales

**Objetivo del Indicador**: medir la extensión (superficie) de los ecosistemas naturales y seminaturales y reportar como proporción del territorio nacional.
**Alcance Espacial**: El reporte debe cubrir la totalidad de la jurisdicción nacional, compuesta por:
- [ ] Territorio Continental e Insular: Basado en límites administrativos.
- [ ] Territorio Marino: Basado en la Zona Económica Exclusiva (ZEE - 200 millas náuticas).

## Fuentes de datos y descripción


A. **Para Ecosistemas Terrestres y Costeros**

Catastro de los Recursos Vegetacionales Nativos de Chile (CONAF) https://sit.conaf.cl/ 
Gestión de la Heterogeneidad Temporal : Dado que el Catastro CONAF no posee un año único de actualización nacional, se debe construir un "Mosaico Nacional".

B. **Para Ecosistemas Marinos**

Capa vectorial de la Zona Económica Exclusiva (ZEE) de Chile. Consultar con Daniel por capa usada para indicador de áreas protegidas

**Capa Complementaria**

Capa de Grupos Funcionales de Ecosistemas (EFG - UICN). (Nota: Esta capa se encuentra en desarrollo).

## Metodología De Procesamiento

El procesamiento se divide en dos flujos que luego se integran.

### Flujo 1: Proccesamiento Terrestre (CONAF)

#### Paso 1.1: Filtrado de Áreas Naturales

Utilizar atributos USO y SUBUSO del Catastro CONAF.

CLASES A INCLUIR:
- [X] Bosque Nativo: (Todos los tipos).
- [X] Praderas y Matorrales: (Matorral, Estepa, Pradera natural).
- [X] Humedales: (Vegas, bofedales, pajonales).
- [X] Áreas desprovistas (Naturales): Desiertos, dunas, playas, nieves, glaciares, roqueríos.
- [X] Cuerpos de Agua: Lagos, lagunas, ríos.

CLASES A EXCLUIR (Descartar):
- [ ] Terrenos Agrícolas, Plantaciones Forestales, Áreas Urbanas/Industriales, Embalses artificiales.

In [1]:
import os
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv("../local.env")
engine = create_engine("postgresql://{user}:{password}@localhost:5432/{dbname}".format(
    dbname=os.environ.get("SEVENNR_DB_NAME"),
    user=os.environ.get("SEVENNR_DB_USER"),
    password=os.environ.get("SEVENNR_DB_PASSWORD"),
))

In [2]:
indicador = pd.read_excel("data/ajuste_a2.xlsx", sheet_name="Hoja2", header=0)
indicador

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Hectares,NaN,Área natural absoluta.
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Hectares,NaN,Área natural absoluta.
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,NaN,Área natural absoluta.
5,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
6,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,NaN,Área natural absoluta.
7,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
8,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Hectares,NaN,Área natural absoluta.
9,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional M...
10,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Hectares,NaN,Área natural absoluta.
11,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
12,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Hectares,NaN,Área natural absoluta.
13,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
14,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Hectares,NaN,Área natural absoluta.
15,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...

In [3]:
%%time
with engine.connect() as conn:
    uso_subuso = pd.read_sql_table("uso_subuso", conn, schema="processed")
uso_subuso

WARNING:  database "7nr" has a collation version mismatch
DETAIL:  The database was created using collation version 2.41, but the operating system provides version 2.31.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE "7nr" REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

CPU times: user 89 ms, sys: 11.2 ms, total: 100 ms
Wall time: 1.96 s

,id_uso,id_subuso,uso,subuso,incluir,superf_ha
0,1,2,Ãreas Urbanas e Industriales,MinerÃ­a Industrial,False,NaN
1,2,1,Terrenos AgrÃ­colas,Terreno de Uso AgrÃ­cola,False,NaN
2,2,2,Terrenos AgrÃ­colas,RotaciÃ³n Cultivo-Pradera,False,NaN
3,3,1,Praderas y Matorrales,Praderas,True,NaN
4,3,2,Praderas y Matorrales,Matorral-Pradera,True,NaN
5,3,3,Praderas y Matorrales,Matorral,True,NaN
6,3,4,Praderas y Matorrales,Matorral Arborescente,True,NaN
7,3,5,Praderas y Matorrales,Matorral con Suculentas,True,NaN
8,3,6,Praderas y Matorrales,FormaciÃ³n de Suculentas,True,NaN
9,3,7,Praderas y Matorrales,PlantaciÃ³n de Arbustos,False,NaN
10,3,8,Praderas y Matorrales,Tundra MagallÃ¡nica,True,NaN
11,4,1,Bosques,PlantaciÃ³n,False,NaN
12,4,2,Bosques,Bosque Nativo,True,NaN
13,4,3,Bosques,Bosque Mixto,True,NaN
14,5,1,Humedales,VegetaciÃ³n HerbÃ¡cea en Orillas de RÃ­os,True,NaN
15,5,2,Humedales,Marismas HerbÃ¡ceas,True,NaN
16,5,3,Humedales,Ã‘adis,True,NaN
17,5,4,Humedales,Turbales,True,NaN
18,5,5,Humedales,Bofedales,True,NaN
19,5,6,Humedales,Vegas,True,NaN
20,5,7,Humedales,Otros Terrenos HÃºmedos,True,NaN
21,6,1,Ãreas Desprovistas de VegetaciÃ³n,Playas y Dunas,True,NaN
22,6,2,Ãreas Desprovistas de VegetaciÃ³n,Afloramientos Rocosos,True,NaN
23,6,3,Ãreas Desprovistas de VegetaciÃ³n,Terrenos sobre el LÃ­mite Altitudinal de la Ve...,True,NaN
24,6,4,Ãreas Desprovistas de VegetaciÃ³n,Corridas de Lavas y Escoriales,True,NaN
25,6,5,Ãreas Desprovistas de VegetaciÃ³n,Derrumbe sin VegetaciÃ³n,True,NaN
26,6,6,Ãreas Desprovistas de VegetaciÃ³n,Salares,True,NaN
27,6,7,Ãreas Desprovistas de VegetaciÃ³n,Otros Terrenos sin VegetaciÃ³n,True,NaN
28,6,8,Ãreas Desprovistas de VegetaciÃ³n,Cajas de RÃ­os,True,NaN
29,7,1,Nieves Eternas y Glaciares,Nieves,True,NaN
30,7,2,Nieves Eternas y Glaciares,Glaciares,True,NaN
31,7,3,Nieves Eternas y Glaciares,Campos de Hielos,True,NaN
32,8,1,Cuerpos de Agua,Mar,True,NaN
33,8,2,Cuerpos de Agua,RÃ­os,True,NaN
34,8,3,Cuerpos de Agua,"Lagos, Lagunas, Embalses, Tranques",True,NaN
35,9,1,ÃƒÂreas no Reconocidas,ÃƒÂreas de Acceso Restringido,False,NaN
36,1,1,Ãreas Urbanas e Industriales,"Ciudades, Pueblos, Zonas Industriales",False,NaN

Procesamiento de datos desde los descargables se realiza a través de un script de python. Los datos estandarizados se registran en una base de datos intermedia.

El área total se calcula sumando la columna `superf_ha` de los datos de CONAF filtrando por la columna de `incluir`:

In [4]:
%%time
with engine.connect() as conn:
    area_natural_terrestre = pd.read_sql_query("""
        SELECT incluir, sum(ct.superf_ha) AS "area"
        FROM processed.conaf_terrestre ct
        	JOIN processed.uso_subuso us
        		ON ct.id_uso = us.id_uso AND ct.id_subuso = us.id_subuso 
        GROUP BY incluir;
    """, conn)
area_natural = area_natural_terrestre.loc[1, 'area']
area_total = area_natural_terrestre["area"].sum()
area_natural_terrestre

CPU times: user 4.1 ms, sys: 2.8 ms, total: 6.91 ms
Wall time: 6.86 s

   incluir          area
0    False  8.479620e+06
1     True  6.720843e+07

In [5]:
area_natural_terrestre["area"].sum()

np.float64(75688051.58420819)

In [6]:
print(f"Área natural total: {area_natural:.2f} ha")
print(f"Porcentaje con el área total: {area_natural*100/area_total:.2f}%")

Área natural total: 67208431.29 ha
Porcentaje con el área total: 88.80%

#### Paso 1.2: Intersección EFG Terrestre (esperar capa EFG)

Cruzar la capa filtrada de CONAF con la capa de Grupos Funcionales UICN para asignar etiquetas (ej. T2.2, T3.2).

Las capas de EFG terrestre y marino fueron unidas por cada grupo funcional y almacenadas en una base de datos intermedia utilizando un script de Python.

Para cada grupo funcional se elimina los polígonos no incluidos como áreas naturales utilizando un nuevo script de Python. Los resultados se almacenan en la base de datos intermedia. Los resultados se muestran consultando a dicha base de datos.

In [7]:
efg_code = pd.read_excel("data/ajuste_a2.xlsx", sheet_name="Hoja1", header=0)
efg_code

,Código EFG,EFG (Ecosystem Functional Group),Realm (Reino)
0,F1.6,Episodic arid rivers,Freshwater
1,F2.9,Geothermal pools and wetlands,Freshwater
2,F2.1,Large permanent freshwater lakes,Freshwater
3,F1.2,Permanent lowland rivers,Freshwater
4,F2.6,Permanent salt and soda lakes,Freshwater
5,F2.3,Seasonal freshwater lakes,Freshwater
6,F2.2,Small permanent freshwater lakes,Freshwater
7,F3.2,Constructed lacustrine wetlands,Freshwater
8,F3.1,Large reservoirs,Freshwater
9,FM1.3,Intermittently closed and open lakes and lagoons,Freshwater-Marine
10,MFT1.3,Coastal saltmarshes and reedbeds,Marine-Freshwater-Terrestrial
11,MT1.2,Muddy Shorelines,Marine-Terrestrial
12,MT1.3,Sandy Shorelines,Marine-Terrestrial
13,T5.5,Hyper-arid deserts,Terrestrial
14,T6.1,"Ice sheets, glaciers and perennial snowfields",Terrestrial
15,T2.3,Oceanic cool temperate rainforests,Terrestrial
16,T6.2,"Polar/alpine cliffs, screes, outcrops and lava...",Terrestrial
17,T3.2,Seasonally dry temperate heath and shrublands,Terrestrial
18,T5.1,Semi-desert steppe,Terrestrial
19,T5.2,Succulent or Thorny deserts and semi-deserts,Terrestrial
20,T6.4,Temperate alpine grasslands and shrublands,Terrestrial
21,T4.5,Temperate subhumid grasslands,Terrestrial
22,T6.5,Tropical alpine grasslands and herbfields,Terrestrial
23,T1.2,Tropical/Subtropical dry forests and thickets,Terrestrial
24,TF1.7,Boreal and temperate fens,Terrestrial-Freshwater
25,TF1.6,"Boreal, temperate and montane peat bogs",Terrestrial-Freshwater
26,TF1.5,Episodic arid floodplains,Terrestrial-Freshwater
27,TF1.4,Seasonal floodplain marshes,Terrestrial-Freshwater

In [8]:
%%time
with engine.connect() as conn:
    efg_terrestre = pd.read_sql_query("""
        SELECT ec."group", ec.superf_ha "area_total", eci.superf_ha "area_natural", eci.superf_ha / ec.superf_ha "porcentaje"
        FROM processed.efg_continental ec
        	JOIN processed.efg_continental_included eci
        		ON ec."group" = eci."group";
    """, conn)
efg_terrestre

CPU times: user 2.6 ms, sys: 1.28 ms, total: 3.88 ms
Wall time: 180 ms

,group,area_total,area_natural,porcentaje
0,Boreal and temperate fens,1.886958e+05,1.852795e+05,0.981895
1,"Boreal, temperate and montane peat bogs",5.350073e+06,5.349428e+06,0.999879
2,Coastal saltmarshes and reedbeds,4.482446e+04,4.436791e+04,0.989815
3,Constructed lacustrine wetlands,5.334631e+02,2.471516e+02,0.463296
4,Episodic arid floodplains,3.025242e+01,8.792613e+00,0.290642
5,Episodic arid rivers,2.385599e+04,2.290089e+04,0.959964
6,Geothermal pools and wetlands,5.501596e+02,5.501596e+02,1.000000
7,Hyper-arid deserts,5.827816e+06,5.612599e+06,0.963071
8,"Ice sheets, glaciers and perennial snowfields",1.806099e+06,1.806082e+06,0.999991
9,Intermittently closed and open lakes and lagoons,1.205930e+04,1.145794e+04,0.950134
10,Large permanent freshwater lakes,1.239736e+06,1.232441e+06,0.994116
11,Large reservoirs,3.615980e+04,2.914710e+04,0.806064
12,Muddy Shorelines,3.519240e+05,3.377234e+05,0.959649
13,Oceanic cool temperate rainforests,2.227194e+07,1.805185e+07,0.810520
14,Permanent lowland rivers,3.564844e+05,3.185748e+05,0.893657
15,Permanent salt and soda lakes,5.475716e+05,5.332370e+05,0.973821
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353077e+06,4.240441e+06,0.974125
17,Sandy Shorelines,9.638001e+02,8.484714e+02,0.880340
18,Seasonal floodplain marshes,2.049620e+05,1.812867e+05,0.884489
19,Seasonal freshwater lakes,4.332678e+02,4.332678e+02,1.000000
20,Seasonally dry temperate heath and shrublands,4.464365e+06,2.456261e+06,0.550193
21,Semi-desert steppe,9.208479e+06,9.059157e+06,0.983784
22,Small permanent freshwater lakes,6.159467e+04,6.108918e+04,0.991793
23,Succulent or Thorny deserts and semi-deserts,4.198207e+06,3.921328e+06,0.934048
24,Temperate alpine grasslands and shrublands,4.125732e+06,4.121051e+06,0.998865
25,Temperate subhumid grasslands,2.369767e+06,2.320867e+06,0.979365
26,Tropical alpine grasslands and herbfields,6.727136e+06,6.706926e+06,0.996996
27,Tropical/Subtropical dry forests and thickets,2.068678e+06,9.845929e+05,0.475953

In [9]:
efg_terrestre = efg_terrestre.merge(efg_code, left_on="group", right_on="EFG (Ecosystem Functional Group)", how="left")
efg_terrestre

,group,area_total,area_natural,porcentaje,Código EFG,EFG (Ecosystem Functional Group),Realm (Reino)
0,Boreal and temperate fens,1.886958e+05,1.852795e+05,0.981895,TF1.7,Boreal and temperate fens,Terrestrial-Freshwater
1,"Boreal, temperate and montane peat bogs",5.350073e+06,5.349428e+06,0.999879,TF1.6,"Boreal, temperate and montane peat bogs",Terrestrial-Freshwater
2,Coastal saltmarshes and reedbeds,4.482446e+04,4.436791e+04,0.989815,MFT1.3,Coastal saltmarshes and reedbeds,Marine-Freshwater-Terrestrial
3,Constructed lacustrine wetlands,5.334631e+02,2.471516e+02,0.463296,F3.2,Constructed lacustrine wetlands,Freshwater
4,Episodic arid floodplains,3.025242e+01,8.792613e+00,0.290642,TF1.5,Episodic arid floodplains,Terrestrial-Freshwater
5,Episodic arid rivers,2.385599e+04,2.290089e+04,0.959964,F1.6,Episodic arid rivers,Freshwater
6,Geothermal pools and wetlands,5.501596e+02,5.501596e+02,1.000000,F2.9,Geothermal pools and wetlands,Freshwater
7,Hyper-arid deserts,5.827816e+06,5.612599e+06,0.963071,T5.5,Hyper-arid deserts,Terrestrial
8,"Ice sheets, glaciers and perennial snowfields",1.806099e+06,1.806082e+06,0.999991,T6.1,"Ice sheets, glaciers and perennial snowfields",Terrestrial
9,Intermittently closed and open lakes and lagoons,1.205930e+04,1.145794e+04,0.950134,FM1.3,Intermittently closed and open lakes and lagoons,Freshwater-Marine
10,Large permanent freshwater lakes,1.239736e+06,1.232441e+06,0.994116,F2.1,Large permanent freshwater lakes,Freshwater
11,Large reservoirs,3.615980e+04,2.914710e+04,0.806064,F3.1,Large reservoirs,Freshwater
12,Muddy Shorelines,3.519240e+05,3.377234e+05,0.959649,MT1.2,Muddy Shorelines,Marine-Terrestrial
13,Oceanic cool temperate rainforests,2.227194e+07,1.805185e+07,0.810520,T2.3,Oceanic cool temperate rainforests,Terrestrial
14,Permanent lowland rivers,3.564844e+05,3.185748e+05,0.893657,F1.2,Permanent lowland rivers,Freshwater
15,Permanent salt and soda lakes,5.475716e+05,5.332370e+05,0.973821,F2.6,Permanent salt and soda lakes,Freshwater
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353077e+06,4.240441e+06,0.974125,T6.2,"Polar/alpine cliffs, screes, outcrops and lava...",Terrestrial
17,Sandy Shorelines,9.638001e+02,8.484714e+02,0.880340,MT1.3,Sandy Shorelines,Marine-Terrestrial
18,Seasonal floodplain marshes,2.049620e+05,1.812867e+05,0.884489,TF1.4,Seasonal floodplain marshes,Terrestrial-Freshwater
19,Seasonal freshwater lakes,4.332678e+02,4.332678e+02,1.000000,F2.3,Seasonal freshwater lakes,Freshwater
20,Seasonally dry temperate heath and shrublands,4.464365e+06,2.456261e+06,0.550193,T3.2,Seasonally dry temperate heath and shrublands,Terrestrial
21,Semi-desert steppe,9.208479e+06,9.059157e+06,0.983784,T5.1,Semi-desert steppe,Terrestrial
22,Small permanent freshwater lakes,6.159467e+04,6.108918e+04,0.991793,F2.2,Small permanent freshwater lakes,Freshwater
23,Succulent or Thorny deserts and semi-deserts,4.198207e+06,3.921328e+06,0.934048,T5.2,Succulent or Thorny deserts and semi-deserts,Terrestrial
24,Temperate alpine grasslands and shrublands,4.125732e+06,4.121051e+06,0.998865,T6.4,Temperate alpine grasslands and shrublands,Terrestrial
25,Temperate subhumid grasslands,2.369767e+06,2.320867e+06,0.979365,T4.5,Temperate subhumid grasslands,Terrestrial
26,Tropical alpine grasslands and herbfields,6.727136e+06,6.706926e+06,0.996996,T6.5,Tropical alpine grasslands and herbfields,Terrestrial
27,Tropical/Subtropical dry forests and thickets,2.068678e+06,9.845929e+05,0.475953,T1.2,Tropical/Subtropical dry forests and thickets,Terrestrial

Limpieza final. Dado que no consideramos EFG antrópicos (los excluimos a través del catastro), de los EFG actuales hay 2 que debemos excluir, y restarlos de las áreas naturales. Estos son: F3.1 (Large reservoirs) y F3.2 (Constructed lacustrine wetlands). Asegurar que la superficie de estos dos EFG no se sume al total de "Áreas Naturales" que se reporte.

In [10]:
efg_terrestre.loc[
    efg_terrestre[efg_terrestre["Código EFG"].isin(["F3.1", "F3.2"])].index,
    ["area_natural", "porcentaje"]
] = 0
efg_terrestre

,group,area_total,area_natural,porcentaje,Código EFG,EFG (Ecosystem Functional Group),Realm (Reino)
0,Boreal and temperate fens,1.886958e+05,1.852795e+05,0.981895,TF1.7,Boreal and temperate fens,Terrestrial-Freshwater
1,"Boreal, temperate and montane peat bogs",5.350073e+06,5.349428e+06,0.999879,TF1.6,"Boreal, temperate and montane peat bogs",Terrestrial-Freshwater
2,Coastal saltmarshes and reedbeds,4.482446e+04,4.436791e+04,0.989815,MFT1.3,Coastal saltmarshes and reedbeds,Marine-Freshwater-Terrestrial
3,Constructed lacustrine wetlands,5.334631e+02,0.000000e+00,0.000000,F3.2,Constructed lacustrine wetlands,Freshwater
4,Episodic arid floodplains,3.025242e+01,8.792613e+00,0.290642,TF1.5,Episodic arid floodplains,Terrestrial-Freshwater
5,Episodic arid rivers,2.385599e+04,2.290089e+04,0.959964,F1.6,Episodic arid rivers,Freshwater
6,Geothermal pools and wetlands,5.501596e+02,5.501596e+02,1.000000,F2.9,Geothermal pools and wetlands,Freshwater
7,Hyper-arid deserts,5.827816e+06,5.612599e+06,0.963071,T5.5,Hyper-arid deserts,Terrestrial
8,"Ice sheets, glaciers and perennial snowfields",1.806099e+06,1.806082e+06,0.999991,T6.1,"Ice sheets, glaciers and perennial snowfields",Terrestrial
9,Intermittently closed and open lakes and lagoons,1.205930e+04,1.145794e+04,0.950134,FM1.3,Intermittently closed and open lakes and lagoons,Freshwater-Marine
10,Large permanent freshwater lakes,1.239736e+06,1.232441e+06,0.994116,F2.1,Large permanent freshwater lakes,Freshwater
11,Large reservoirs,3.615980e+04,0.000000e+00,0.000000,F3.1,Large reservoirs,Freshwater
12,Muddy Shorelines,3.519240e+05,3.377234e+05,0.959649,MT1.2,Muddy Shorelines,Marine-Terrestrial
13,Oceanic cool temperate rainforests,2.227194e+07,1.805185e+07,0.810520,T2.3,Oceanic cool temperate rainforests,Terrestrial
14,Permanent lowland rivers,3.564844e+05,3.185748e+05,0.893657,F1.2,Permanent lowland rivers,Freshwater
15,Permanent salt and soda lakes,5.475716e+05,5.332370e+05,0.973821,F2.6,Permanent salt and soda lakes,Freshwater
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353077e+06,4.240441e+06,0.974125,T6.2,"Polar/alpine cliffs, screes, outcrops and lava...",Terrestrial
17,Sandy Shorelines,9.638001e+02,8.484714e+02,0.880340,MT1.3,Sandy Shorelines,Marine-Terrestrial
18,Seasonal floodplain marshes,2.049620e+05,1.812867e+05,0.884489,TF1.4,Seasonal floodplain marshes,Terrestrial-Freshwater
19,Seasonal freshwater lakes,4.332678e+02,4.332678e+02,1.000000,F2.3,Seasonal freshwater lakes,Freshwater
20,Seasonally dry temperate heath and shrublands,4.464365e+06,2.456261e+06,0.550193,T3.2,Seasonally dry temperate heath and shrublands,Terrestrial
21,Semi-desert steppe,9.208479e+06,9.059157e+06,0.983784,T5.1,Semi-desert steppe,Terrestrial
22,Small permanent freshwater lakes,6.159467e+04,6.108918e+04,0.991793,F2.2,Small permanent freshwater lakes,Freshwater
23,Succulent or Thorny deserts and semi-deserts,4.198207e+06,3.921328e+06,0.934048,T5.2,Succulent or Thorny deserts and semi-deserts,Terrestrial
24,Temperate alpine grasslands and shrublands,4.125732e+06,4.121051e+06,0.998865,T6.4,Temperate alpine grasslands and shrublands,Terrestrial
25,Temperate subhumid grasslands,2.369767e+06,2.320867e+06,0.979365,T4.5,Temperate subhumid grasslands,Terrestrial
26,Tropical alpine grasslands and herbfields,6.727136e+06,6.706926e+06,0.996996,T6.5,Tropical alpine grasslands and herbfields,Terrestrial
27,Tropical/Subtropical dry forests and thickets,2.068678e+06,9.845929e+05,0.475953,T1.2,Tropical/Subtropical dry forests and thickets,Terrestrial

In [11]:
area_natural_continental = efg_terrestre['area_natural'].sum()
area_continental = efg_terrestre['area_total'].sum()

print(f"Área Natural total: {area_natural_continental:.2f} ha")
print(f"Área total: {area_continental:.2f} ha")

Área Natural total: 67560784.25 ha
Área total: 75841745.84 ha

Agrupar por _Realm_:

In [12]:
efg_realm = efg_terrestre.groupby("Realm (Reino)").sum("area_natural")
efg_realm

                                 area_total  area_natural  porcentaje
Realm (Reino)
Freshwater                     2.266919e+06  2.169227e+06    6.813352
Freshwater-Marine              1.205930e+04  1.145794e+04    0.950134
Marine-Freshwater-Terrestrial  4.482446e+04  4.436791e+04    0.989815
Marine-Terrestrial             3.528878e+05  3.385719e+05    1.839988
Terrestrial                    6.742129e+07  5.928116e+07    9.666911
Terrestrial-Freshwater         5.743761e+06  5.716003e+06    3.156906

In [13]:
for realm, row in efg_realm.iterrows():
    mask = (
        (indicador["Disaggregation type"] == "Realm") &
        (indicador["Disaggregation"] == realm)
    )
    if len(indicador[mask]) == 0:
        continue
    else:
        mask_hectares = mask & (indicador["Unit"] == "Hectares")
        indicador.loc[indicador[mask_hectares].index, "Value"] = row["area_natural"]
        mask_percent = mask & (indicador["Unit"] == "Percent")
        indicador.loc[indicador[mask_percent].index, "Value"] = row["area_natural"] * 100 / area_continental
indicador

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Hectares,5.928116e+07,Área natural absoluta.
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Percent,7.816428e+01,Porcentaje respecto a la Superficie Nacional C...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Hectares,5.716003e+06,Área natural absoluta.
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Percent,7.536750e+00,Porcentaje respecto a la Superficie Nacional C...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.145794e+04,Área natural absoluta.
5,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.510770e-02,Porcentaje respecto a la Superficie Nacional C...
6,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436791e+04,Área natural absoluta.
7,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Percent,5.850065e-02,Porcentaje respecto a la Superficie Nacional C...
8,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Hectares,NaN,Área natural absoluta.
9,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional M...
10,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Hectares,NaN,Área natural absoluta.
11,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
12,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Hectares,NaN,Área natural absoluta.
13,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...
14,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Hectares,NaN,Área natural absoluta.
15,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional C...

Agregar indicadores desagregados por _Ecosystem Functional Group_:

In [14]:
mask = indicador["Disaggregation type"] == "Ecosystem Functional Group"
disaggregations = pd.unique(indicador[mask]["Disaggregation"])
for efg in disaggregations:
    code = efg.split(" ")[0]
    curr_mask = mask & (indicador["Disaggregation"] == efg) 
    area = efg_terrestre[efg_terrestre["Código EFG"] == code]["area_natural"].iloc[0]
    mask_hectares = curr_mask & (indicador["Unit"] == "Hectares")
    indicador.loc[indicador[curr_mask & (indicador["Unit"] == "Hectares")].index, "Value"] = area
    indicador.loc[indicador[curr_mask & (indicador["Unit"] == "Percent")].index, "Value"] = area * 100 / area_continental
indicador

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Hectares,5.928116e+07,Área natural absoluta.
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Percent,7.816428e+01,Porcentaje respecto a la Superficie Nacional C...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Hectares,5.716003e+06,Área natural absoluta.
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Percent,7.536750e+00,Porcentaje respecto a la Superficie Nacional C...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.145794e+04,Área natural absoluta.
5,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.510770e-02,Porcentaje respecto a la Superficie Nacional C...
6,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436791e+04,Área natural absoluta.
7,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Percent,5.850065e-02,Porcentaje respecto a la Superficie Nacional C...
8,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Hectares,NaN,Área natural absoluta.
9,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Percent,NaN,Porcentaje respecto a la Superficie Nacional M...
10,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Hectares,5.349428e+06,Área natural absoluta.
11,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Percent,7.053408e+00,Porcentaje respecto a la Superficie Nacional C...
12,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Hectares,4.436791e+04,Área natural absoluta.
13,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Percent,5.850065e-02,Porcentaje respecto a la Superficie Nacional C...
14,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Hectares,1.145794e+04,Área natural absoluta.
15,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Percent,1.510770e-02,Porcentaje respecto a la Superficie Nacional C...

### Flujo 2: Procesamiento Marino

#### Paso 2.1: Generación de la Capa Marina

Utilizar el polígono de la ZEE (200 millas).
Exclusión: Restar cualquier área que ya esté cubierta por el Catastro CONAF en la zona costera (ej. fiordos interiores o islas) para evitar doble contabilidad.

Ambos procesos se realizan en un script de python que elimina las intersecciones.

#### Paso 2.2: Intersección EFG Marino  (esperar capa EFG)

Cruzar el polígono de la ZEE con la capa de Grupos Funcionales Marinos de la UICN.
Esto clasificará el mar en grupos como M2 (Océano abierto pelágico), M3 (Mar profundo), etc.
> Nota: Se asume que toda la extensión de la ZEE es "Ecosistema Natural" a menos que existan capas específicas de "infraestructura marina artificial" (granjas eólicas, plataformas) que deban restarse (Clase M4/MT3). Ante la falta de datos de infraestructura marina, se contabiliza la ZEE total.

In [15]:
%%time
with engine.connect() as conn:
    efg_marino = pd.read_sql_query("""
        SELECT em."group", em.superf_ha "area_total", em.superf_ha "area_natural", em.superf_ha / em.superf_ha "porcentaje"
        FROM processed.efg_marino em;
    """, conn)
efg_marino

CPU times: user 1.71 ms, sys: 705 μs, total: 2.41 ms
Wall time: 221 ms

                                group    area_total  area_natural  porcentaje
0                      Abyssal plains  2.923908e+08  2.923908e+08         1.0
1   Coastal shrublands and grasslands  1.890645e+05  1.890645e+05         1.0
2       Continental and island slopes  5.634470e+07  5.634470e+07         1.0
3            Deepwater coastal inlets  7.370096e+06  7.370096e+06         1.0
4          Hadal trenches and troughs  3.877248e+06  3.877248e+06         1.0
5                        Kelp forests  1.201602e+07  1.201602e+07         1.0
6                    Rocky Shorelines  2.587972e+05  2.587972e+05         1.0
7                    Sandy Shorelines  4.507395e+05  4.507395e+05         1.0
8      Seamounts, ridges and plateaus  1.685113e+07  1.685113e+07         1.0
9                Subtidal rocky reefs  6.509729e+05  6.509729e+05         1.0
10                 Subtidal sand beds  2.826118e+06  2.826118e+06         1.0
11                    Upwelling zones  3.794770e+05  3.794770e+05         1.0

In [16]:
efg_marino_total = efg_marino["area_natural"].sum()
print(f"Área natural marino: {efg_marino_total:.2f} ha")

Área natural marino: 393605147.88 ha

In [17]:
mask = (
    (indicador["Disaggregation type"] == "Realm") &
    (indicador["Disaggregation"] == "Marine")
)
indicador.loc[indicador[mask & (indicador["Unit"] == "Hectares")].index, "Value"] = efg_marino_total
indicador.loc[indicador[mask & (indicador["Unit"] == "Percent")].index, "Value"] = efg_marino_total * 100 / efg_marino_total
indicador

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Hectares,5.928116e+07,Área natural absoluta.
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Percent,7.816428e+01,Porcentaje respecto a la Superficie Nacional C...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Hectares,5.716003e+06,Área natural absoluta.
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Percent,7.536750e+00,Porcentaje respecto a la Superficie Nacional C...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.145794e+04,Área natural absoluta.
5,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.510770e-02,Porcentaje respecto a la Superficie Nacional C...
6,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436791e+04,Área natural absoluta.
7,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Percent,5.850065e-02,Porcentaje respecto a la Superficie Nacional C...
8,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Hectares,3.936051e+08,Área natural absoluta.
9,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Percent,1.000000e+02,Porcentaje respecto a la Superficie Nacional M...
10,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Hectares,5.349428e+06,Área natural absoluta.
11,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,TF1.6 Boreal temperate and montane peat bogs,2024,Percent,7.053408e+00,Porcentaje respecto a la Superficie Nacional C...
12,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Hectares,4.436791e+04,Área natural absoluta.
13,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,MFT1.3 Coastal saltmarshes and reedbeds,2024,Percent,5.850065e-02,Porcentaje respecto a la Superficie Nacional C...
14,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Hectares,1.145794e+04,Área natural absoluta.
15,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,FM1.3 Intermittently closed and open lakes and...,2024,Percent,1.510770e-02,Porcentaje respecto a la Superficie Nacional C...

### Paso 3: Integración y Cálculo

Unificar los resultados del Flujo 1 y Flujo 2.
Superficie Natural Total = (Sup. Natural CONAF) + (Sup. ZEE Natural).
Superficie Total País = Sup. Terrestre Oficial + Sup. ZEE Oficial.
Calcular proporción de áreas naturales en el territorio nacional

In [18]:
area_natural_total = area_natural + efg_marino_total
print(f"Área natural total (terrestre + marino): {area_natural_total:.2f} ha")

Área natural total (terrestre + marino): 460813579.17 ha

In [19]:
indicador.to_csv("indicador_a_2.csv", header=True, index=False)