# A.2 Extensión de ecosistemas naturales

**Objetivo del Indicador**: medir la extensión (superficie) de los ecosistemas naturales y seminaturales y reportar como proporción del territorio nacional.
**Alcance Espacial**: El reporte debe cubrir la totalidad de la jurisdicción nacional, compuesta por:
- [ ] Territorio Continental e Insular: Basado en límites administrativos.
- [ ] Territorio Marino: Basado en la Zona Económica Exclusiva (ZEE - 200 millas náuticas).

## Fuentes de datos y descripción


A. **Para Ecosistemas Terrestres y Costeros**

Catastro de los Recursos Vegetacionales Nativos de Chile (CONAF) https://sit.conaf.cl/ 
Gestión de la Heterogeneidad Temporal : Dado que el Catastro CONAF no posee un año único de actualización nacional, se debe construir un "Mosaico Nacional".

B. **Para Ecosistemas Marinos**

Capa vectorial de la Zona Económica Exclusiva (ZEE) de Chile. Consultar con Daniel por capa usada para indicador de áreas protegidas

**Capa Complementaria**

Capa de Grupos Funcionales de Ecosistemas (EFG - UICN). (Nota: Esta capa se encuentra en desarrollo).

## Metodología De Procesamiento

El procesamiento se divide en dos flujos que luego se integran.

### Flujo 1: Proccesamiento Terrestre (CONAF)

#### Paso 1.1: Filtrado de Áreas Naturales

Utilizar atributos USO y SUBUSO del Catastro CONAF.

CLASES A INCLUIR:
- [X] Bosque Nativo: (Todos los tipos).
- [X] Praderas y Matorrales: (Matorral, Estepa, Pradera natural).
- [X] Humedales: (Vegas, bofedales, pajonales).
- [X] Áreas desprovistas (Naturales): Desiertos, dunas, playas, nieves, glaciares, roqueríos.
- [X] Cuerpos de Agua: Lagos, lagunas, ríos.

CLASES A EXCLUIR (Descartar):
- [ ] Terrenos Agrícolas, Plantaciones Forestales, Áreas Urbanas/Industriales, Embalses artificiales.

In [1]:
import os
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv("../local.env")
engine = create_engine("postgresql://{user}:{password}@localhost:5432/{dbname}".format(
    dbname=os.environ.get("SEVENNR_DB_NAME"),
    user=os.environ.get("SEVENNR_DB_USER"),
    password=os.environ.get("SEVENNR_DB_PASSWORD"),
))

In [2]:
indicator_columns = [
    "Indicator code", "Indicator",
    "Does this data row represent a disaggregation",
    "Disaggregation type", "Disaggregation",
    "Year", "Unit", "Value", "Footnote"
]
indicator = pd.DataFrame(list(), columns=indicator_columns)
indicator_code = "A.2"
indicator_name = "A.2 Extent of natural ecosystems"
is_disaggregation = "True"
year_indicator = 2024
hectares_footnote_continental = "Absolute natural and semi-natural extent in the continental territory"
hectares_footnote_marine = "Absolute natural and semi-natural extent in the marine territory"
percent_footnote_continental = "Percentage relative to the total national continental extent"
percent_footnote_marine = "Percentage relative to the total national marine extent"
indicator

Empty DataFrame
Columns: [Indicator code, Indicator, Does this data row represent a disaggregation, Disaggregation type, Disaggregation, Year, Unit, Value, Footnote]
Index: []

In [3]:
%%time
with engine.connect() as conn:
    uso_subuso = pd.read_sql_table("uso_subuso", conn, schema="processed")
uso_subuso

WARNING:  database "7nr" has a collation version mismatch
DETAIL:  The database was created using collation version 2.41, but the operating system provides version 2.31.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE "7nr" REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

CPU times: user 117 ms, sys: 12.1 ms, total: 129 ms
Wall time: 2.5 s

,id_uso,id_subuso,uso,subuso,incluir,superf_ha
0,1,2,Ãreas Urbanas e Industriales,MinerÃ­a Industrial,False,NaN
1,2,1,Terrenos AgrÃ­colas,Terreno de Uso AgrÃ­cola,False,NaN
2,2,2,Terrenos AgrÃ­colas,RotaciÃ³n Cultivo-Pradera,False,NaN
3,3,1,Praderas y Matorrales,Praderas,True,NaN
4,3,2,Praderas y Matorrales,Matorral-Pradera,True,NaN
5,3,3,Praderas y Matorrales,Matorral,True,NaN
6,3,4,Praderas y Matorrales,Matorral Arborescente,True,NaN
7,3,5,Praderas y Matorrales,Matorral con Suculentas,True,NaN
8,3,6,Praderas y Matorrales,FormaciÃ³n de Suculentas,True,NaN
9,3,7,Praderas y Matorrales,PlantaciÃ³n de Arbustos,False,NaN
10,3,8,Praderas y Matorrales,Tundra MagallÃ¡nica,True,NaN
11,4,1,Bosques,PlantaciÃ³n,False,NaN
12,4,2,Bosques,Bosque Nativo,True,NaN
13,4,3,Bosques,Bosque Mixto,True,NaN
14,5,1,Humedales,VegetaciÃ³n HerbÃ¡cea en Orillas de RÃ­os,True,NaN
15,5,2,Humedales,Marismas HerbÃ¡ceas,True,NaN
16,5,3,Humedales,Ã‘adis,True,NaN
17,5,4,Humedales,Turbales,True,NaN
18,5,5,Humedales,Bofedales,True,NaN
19,5,6,Humedales,Vegas,True,NaN
20,5,7,Humedales,Otros Terrenos HÃºmedos,True,NaN
21,6,1,Ãreas Desprovistas de VegetaciÃ³n,Playas y Dunas,True,NaN
22,6,2,Ãreas Desprovistas de VegetaciÃ³n,Afloramientos Rocosos,True,NaN
23,6,3,Ãreas Desprovistas de VegetaciÃ³n,Terrenos sobre el LÃ­mite Altitudinal de la Ve...,True,NaN
24,6,4,Ãreas Desprovistas de VegetaciÃ³n,Corridas de Lavas y Escoriales,True,NaN
25,6,5,Ãreas Desprovistas de VegetaciÃ³n,Derrumbe sin VegetaciÃ³n,True,NaN
26,6,6,Ãreas Desprovistas de VegetaciÃ³n,Salares,True,NaN
27,6,7,Ãreas Desprovistas de VegetaciÃ³n,Otros Terrenos sin VegetaciÃ³n,True,NaN
28,6,8,Ãreas Desprovistas de VegetaciÃ³n,Cajas de RÃ­os,True,NaN
29,7,1,Nieves Eternas y Glaciares,Nieves,True,NaN
30,7,2,Nieves Eternas y Glaciares,Glaciares,True,NaN
31,7,3,Nieves Eternas y Glaciares,Campos de Hielos,True,NaN
32,8,1,Cuerpos de Agua,Mar,True,NaN
33,8,2,Cuerpos de Agua,RÃ­os,True,NaN
34,8,3,Cuerpos de Agua,"Lagos, Lagunas, Embalses, Tranques",True,NaN
35,9,1,ÃƒÂreas no Reconocidas,ÃƒÂreas de Acceso Restringido,False,NaN
36,1,1,Ãreas Urbanas e Industriales,"Ciudades, Pueblos, Zonas Industriales",False,NaN

Procesamiento de datos desde los descargables se realiza a través de un script de python. Los datos estandarizados se registran en una base de datos intermedia.

El área total se calcula sumando la columna `superf_ha` de los datos de CONAF filtrando por la columna de `incluir`:

In [4]:
%%time
with engine.connect() as conn:
    area_natural_terrestre = pd.read_sql_query("""
        SELECT incluir, sum(ct.superf_ha) AS "area"
        FROM processed.conaf_terrestre ct
        	JOIN processed.uso_subuso us
        		ON ct.id_uso = us.id_uso AND ct.id_subuso = us.id_subuso 
        GROUP BY incluir;
    """, conn)
area_natural = area_natural_terrestre.loc[1, 'area']
area_total = area_natural_terrestre["area"].sum()
area_natural_terrestre

CPU times: user 3.66 ms, sys: 3 ms, total: 6.66 ms
Wall time: 5.68 s

   incluir          area
0    False  8.479620e+06
1     True  6.720843e+07

In [5]:
print(f"Área natural total: {area_natural:.2f} ha")
print(f"Porcentaje con el área total: {area_natural * 100 / area_total:.2f}%")

Área natural total: 67208431.29 ha
Porcentaje con el área total: 88.80%

#### Paso 1.2: Intersección EFG Terrestre (esperar capa EFG)

Cruzar la capa filtrada de CONAF con la capa de Grupos Funcionales UICN para asignar etiquetas (ej. T2.2, T3.2).

Las capas de EFG terrestre y marino fueron unidas por cada grupo funcional y almacenadas en una base de datos intermedia utilizando un script de Python.

Para cada grupo funcional se elimina los polígonos no incluidos como áreas naturales utilizando un nuevo script de Python. Los resultados se almacenan en la base de datos intermedia. Los resultados se muestran consultando a dicha base de datos.

In [6]:
efg_code_continental = pd.read_excel("data/ajuste_a2.xlsx", sheet_name="EFG_continental", header=0)
efg_code_continental

,Código EFG,EFG (Ecosystem Functional Group),Realm (Reino)
0,F1.6,Episodic arid rivers,Freshwater
1,F2.9,Geothermal pools and wetlands,Freshwater
2,F2.1,Large permanent freshwater lakes,Freshwater
3,F1.2,Permanent lowland rivers,Freshwater
4,F2.6,Permanent salt and soda lakes,Freshwater
5,F2.3,Seasonal freshwater lakes,Freshwater
6,F2.2,Small permanent freshwater lakes,Freshwater
7,F3.2,Constructed lacustrine wetlands,Freshwater
8,F3.1,Large reservoirs,Freshwater
9,FM1.3,Intermittently closed and open lakes and lagoons,Freshwater-Marine
10,MFT1.3,Coastal saltmarshes and reedbeds,Marine-Freshwater-Terrestrial
11,MT1.2,Muddy Shorelines,Marine-Terrestrial
12,MT1.3,Sandy Shorelines,Marine-Terrestrial
13,T5.5,Hyper-arid deserts,Terrestrial
14,T6.1,"Ice sheets, glaciers and perennial snowfields",Terrestrial
15,T2.3,Oceanic cool temperate rainforests,Terrestrial
16,T6.2,"Polar/alpine cliffs, screes, outcrops and lava...",Terrestrial
17,T3.2,Seasonally dry temperate heath and shrublands,Terrestrial
18,T5.1,Semi-desert steppe,Terrestrial
19,T5.2,Succulent or Thorny deserts and semi-deserts,Terrestrial
20,T6.4,Temperate alpine grasslands and shrublands,Terrestrial
21,T4.5,Temperate subhumid grasslands,Terrestrial
22,T6.5,Tropical alpine grasslands and herbfields,Terrestrial
23,T1.2,Tropical/Subtropical dry forests and thickets,Terrestrial
24,TF1.7,Boreal and temperate fens,Terrestrial-Freshwater
25,TF1.6,"Boreal, temperate and montane peat bogs",Terrestrial-Freshwater
26,TF1.5,Episodic arid floodplains,Terrestrial-Freshwater
27,TF1.4,Seasonal floodplain marshes,Terrestrial-Freshwater

In [7]:
%%time
with engine.connect() as conn:
    efg_terrestre = pd.read_sql_query("""
        SELECT ec."group", ec.superf_ha "area_total", eci.superf_ha "area_natural", eci.superf_ha / ec.superf_ha "porcentaje"
        FROM processed.efg_continental ec
        	JOIN processed.efg_continental_included eci
        		ON ec."group" = eci."group";
    """, conn)
efg_terrestre

CPU times: user 1.63 ms, sys: 900 μs, total: 2.53 ms
Wall time: 165 ms

,group,area_total,area_natural,porcentaje
0,Boreal and temperate fens,1.886605e+05,1.852460e+05,0.981901
1,"Boreal, temperate and montane peat bogs",5.339774e+06,5.339129e+06,0.999879
2,Coastal saltmarshes and reedbeds,4.481831e+04,4.436208e+04,0.989820
3,Constructed lacustrine wetlands,5.329274e+02,2.469162e+02,0.463321
4,Episodic arid floodplains,3.023341e+01,8.787016e+00,0.290639
5,Episodic arid rivers,2.385206e+04,2.289754e+04,0.959982
6,Geothermal pools and wetlands,5.504601e+02,5.504601e+02,1.000000
7,Hyper-arid deserts,5.831525e+06,5.616169e+06,0.963070
8,"Ice sheets, glaciers and perennial snowfields",1.803515e+06,1.803491e+06,0.999987
9,Intermittently closed and open lakes and lagoons,1.202678e+04,1.142688e+04,0.950120
10,Large permanent freshwater lakes,1.238061e+06,1.230773e+06,0.994113
11,Large reservoirs,3.615045e+04,2.913902e+04,0.806049
12,Muddy Shorelines,3.517156e+05,3.375230e+05,0.959648
13,Oceanic cool temperate rainforests,2.223725e+07,1.802447e+07,0.810553
14,Permanent lowland rivers,3.560821e+05,3.182078e+05,0.893636
15,Permanent salt and soda lakes,5.479433e+05,5.335984e+05,0.973820
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353149e+06,4.240688e+06,0.974166
17,Sandy Shorelines,9.610201e+02,8.460005e+02,0.880315
18,Seasonal floodplain marshes,2.047453e+05,1.811106e+05,0.884566
19,Seasonal freshwater lakes,4.335966e+02,4.335966e+02,1.000000
20,Seasonally dry temperate heath and shrublands,4.461955e+06,2.455579e+06,0.550337
21,Semi-desert steppe,9.213948e+06,9.064530e+06,0.983783
22,Small permanent freshwater lakes,6.156128e+04,6.105619e+04,0.991795
23,Succulent or Thorny deserts and semi-deserts,4.197980e+06,3.921172e+06,0.934062
24,Temperate alpine grasslands and shrublands,4.125285e+06,4.120602e+06,0.998865
25,Temperate subhumid grasslands,2.370603e+06,2.321693e+06,0.979368
26,Tropical alpine grasslands and herbfields,6.731423e+06,6.711197e+06,0.996995
27,Tropical/Subtropical dry forests and thickets,2.068229e+06,9.845399e+05,0.476030

In [8]:
efg_terrestre = efg_terrestre.merge(efg_code_continental, left_on="group", right_on="EFG (Ecosystem Functional Group)", how="left")
efg_terrestre

,group,area_total,area_natural,porcentaje,Código EFG,EFG (Ecosystem Functional Group),Realm (Reino)
0,Boreal and temperate fens,1.886605e+05,1.852460e+05,0.981901,TF1.7,Boreal and temperate fens,Terrestrial-Freshwater
1,"Boreal, temperate and montane peat bogs",5.339774e+06,5.339129e+06,0.999879,TF1.6,"Boreal, temperate and montane peat bogs",Terrestrial-Freshwater
2,Coastal saltmarshes and reedbeds,4.481831e+04,4.436208e+04,0.989820,MFT1.3,Coastal saltmarshes and reedbeds,Marine-Freshwater-Terrestrial
3,Constructed lacustrine wetlands,5.329274e+02,2.469162e+02,0.463321,F3.2,Constructed lacustrine wetlands,Freshwater
4,Episodic arid floodplains,3.023341e+01,8.787016e+00,0.290639,TF1.5,Episodic arid floodplains,Terrestrial-Freshwater
5,Episodic arid rivers,2.385206e+04,2.289754e+04,0.959982,F1.6,Episodic arid rivers,Freshwater
6,Geothermal pools and wetlands,5.504601e+02,5.504601e+02,1.000000,F2.9,Geothermal pools and wetlands,Freshwater
7,Hyper-arid deserts,5.831525e+06,5.616169e+06,0.963070,T5.5,Hyper-arid deserts,Terrestrial
8,"Ice sheets, glaciers and perennial snowfields",1.803515e+06,1.803491e+06,0.999987,T6.1,"Ice sheets, glaciers and perennial snowfields",Terrestrial
9,Intermittently closed and open lakes and lagoons,1.202678e+04,1.142688e+04,0.950120,FM1.3,Intermittently closed and open lakes and lagoons,Freshwater-Marine
10,Large permanent freshwater lakes,1.238061e+06,1.230773e+06,0.994113,F2.1,Large permanent freshwater lakes,Freshwater
11,Large reservoirs,3.615045e+04,2.913902e+04,0.806049,F3.1,Large reservoirs,Freshwater
12,Muddy Shorelines,3.517156e+05,3.375230e+05,0.959648,MT1.2,Muddy Shorelines,Marine-Terrestrial
13,Oceanic cool temperate rainforests,2.223725e+07,1.802447e+07,0.810553,T2.3,Oceanic cool temperate rainforests,Terrestrial
14,Permanent lowland rivers,3.560821e+05,3.182078e+05,0.893636,F1.2,Permanent lowland rivers,Freshwater
15,Permanent salt and soda lakes,5.479433e+05,5.335984e+05,0.973820,F2.6,Permanent salt and soda lakes,Freshwater
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353149e+06,4.240688e+06,0.974166,T6.2,"Polar/alpine cliffs, screes, outcrops and lava...",Terrestrial
17,Sandy Shorelines,9.610201e+02,8.460005e+02,0.880315,MT1.3,Sandy Shorelines,Marine-Terrestrial
18,Seasonal floodplain marshes,2.047453e+05,1.811106e+05,0.884566,TF1.4,Seasonal floodplain marshes,Terrestrial-Freshwater
19,Seasonal freshwater lakes,4.335966e+02,4.335966e+02,1.000000,F2.3,Seasonal freshwater lakes,Freshwater
20,Seasonally dry temperate heath and shrublands,4.461955e+06,2.455579e+06,0.550337,T3.2,Seasonally dry temperate heath and shrublands,Terrestrial
21,Semi-desert steppe,9.213948e+06,9.064530e+06,0.983783,T5.1,Semi-desert steppe,Terrestrial
22,Small permanent freshwater lakes,6.156128e+04,6.105619e+04,0.991795,F2.2,Small permanent freshwater lakes,Freshwater
23,Succulent or Thorny deserts and semi-deserts,4.197980e+06,3.921172e+06,0.934062,T5.2,Succulent or Thorny deserts and semi-deserts,Terrestrial
24,Temperate alpine grasslands and shrublands,4.125285e+06,4.120602e+06,0.998865,T6.4,Temperate alpine grasslands and shrublands,Terrestrial
25,Temperate subhumid grasslands,2.370603e+06,2.321693e+06,0.979368,T4.5,Temperate subhumid grasslands,Terrestrial
26,Tropical alpine grasslands and herbfields,6.731423e+06,6.711197e+06,0.996995,T6.5,Tropical alpine grasslands and herbfields,Terrestrial
27,Tropical/Subtropical dry forests and thickets,2.068229e+06,9.845399e+05,0.476030,T1.2,Tropical/Subtropical dry forests and thickets,Terrestrial

Limpieza final. Dado que no consideramos EFG antrópicos (los excluimos a través del catastro), de los EFG actuales hay 2 que debemos excluir, y restarlos de las áreas naturales. Estos son: F3.1 (Large reservoirs) y F3.2 (Constructed lacustrine wetlands). Asegurar que la superficie de estos dos EFG no se sume al total de "Áreas Naturales" que se reporte.

In [9]:
efg_terrestre.loc[
    efg_terrestre[efg_terrestre["Código EFG"].isin(["F3.1", "F3.2"])].index,
    ["area_natural", "porcentaje"]
] = 0
efg_terrestre

,group,area_total,area_natural,porcentaje,Código EFG,EFG (Ecosystem Functional Group),Realm (Reino)
0,Boreal and temperate fens,1.886605e+05,1.852460e+05,0.981901,TF1.7,Boreal and temperate fens,Terrestrial-Freshwater
1,"Boreal, temperate and montane peat bogs",5.339774e+06,5.339129e+06,0.999879,TF1.6,"Boreal, temperate and montane peat bogs",Terrestrial-Freshwater
2,Coastal saltmarshes and reedbeds,4.481831e+04,4.436208e+04,0.989820,MFT1.3,Coastal saltmarshes and reedbeds,Marine-Freshwater-Terrestrial
3,Constructed lacustrine wetlands,5.329274e+02,0.000000e+00,0.000000,F3.2,Constructed lacustrine wetlands,Freshwater
4,Episodic arid floodplains,3.023341e+01,8.787016e+00,0.290639,TF1.5,Episodic arid floodplains,Terrestrial-Freshwater
5,Episodic arid rivers,2.385206e+04,2.289754e+04,0.959982,F1.6,Episodic arid rivers,Freshwater
6,Geothermal pools and wetlands,5.504601e+02,5.504601e+02,1.000000,F2.9,Geothermal pools and wetlands,Freshwater
7,Hyper-arid deserts,5.831525e+06,5.616169e+06,0.963070,T5.5,Hyper-arid deserts,Terrestrial
8,"Ice sheets, glaciers and perennial snowfields",1.803515e+06,1.803491e+06,0.999987,T6.1,"Ice sheets, glaciers and perennial snowfields",Terrestrial
9,Intermittently closed and open lakes and lagoons,1.202678e+04,1.142688e+04,0.950120,FM1.3,Intermittently closed and open lakes and lagoons,Freshwater-Marine
10,Large permanent freshwater lakes,1.238061e+06,1.230773e+06,0.994113,F2.1,Large permanent freshwater lakes,Freshwater
11,Large reservoirs,3.615045e+04,0.000000e+00,0.000000,F3.1,Large reservoirs,Freshwater
12,Muddy Shorelines,3.517156e+05,3.375230e+05,0.959648,MT1.2,Muddy Shorelines,Marine-Terrestrial
13,Oceanic cool temperate rainforests,2.223725e+07,1.802447e+07,0.810553,T2.3,Oceanic cool temperate rainforests,Terrestrial
14,Permanent lowland rivers,3.560821e+05,3.182078e+05,0.893636,F1.2,Permanent lowland rivers,Freshwater
15,Permanent salt and soda lakes,5.479433e+05,5.335984e+05,0.973820,F2.6,Permanent salt and soda lakes,Freshwater
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353149e+06,4.240688e+06,0.974166,T6.2,"Polar/alpine cliffs, screes, outcrops and lava...",Terrestrial
17,Sandy Shorelines,9.610201e+02,8.460005e+02,0.880315,MT1.3,Sandy Shorelines,Marine-Terrestrial
18,Seasonal floodplain marshes,2.047453e+05,1.811106e+05,0.884566,TF1.4,Seasonal floodplain marshes,Terrestrial-Freshwater
19,Seasonal freshwater lakes,4.335966e+02,4.335966e+02,1.000000,F2.3,Seasonal freshwater lakes,Freshwater
20,Seasonally dry temperate heath and shrublands,4.461955e+06,2.455579e+06,0.550337,T3.2,Seasonally dry temperate heath and shrublands,Terrestrial
21,Semi-desert steppe,9.213948e+06,9.064530e+06,0.983783,T5.1,Semi-desert steppe,Terrestrial
22,Small permanent freshwater lakes,6.156128e+04,6.105619e+04,0.991795,F2.2,Small permanent freshwater lakes,Freshwater
23,Succulent or Thorny deserts and semi-deserts,4.197980e+06,3.921172e+06,0.934062,T5.2,Succulent or Thorny deserts and semi-deserts,Terrestrial
24,Temperate alpine grasslands and shrublands,4.125285e+06,4.120602e+06,0.998865,T6.4,Temperate alpine grasslands and shrublands,Terrestrial
25,Temperate subhumid grasslands,2.370603e+06,2.321693e+06,0.979368,T4.5,Temperate subhumid grasslands,Terrestrial
26,Tropical alpine grasslands and herbfields,6.731423e+06,6.711197e+06,0.996995,T6.5,Tropical alpine grasslands and herbfields,Terrestrial
27,Tropical/Subtropical dry forests and thickets,2.068229e+06,9.845399e+05,0.476030,T1.2,Tropical/Subtropical dry forests and thickets,Terrestrial

In [10]:
area_natural_continental = efg_terrestre['area_natural'].sum()
area_continental = efg_terrestre['area_total'].sum()

print(f"Área Natural total: {area_natural_continental:.2f} ha")
print(f"Área total: {area_continental:.2f} ha")

Área Natural total: 67531297.03 ha
Área total: 75802764.30 ha

Agrupar por _Realm_:

In [11]:
efg_realm_continental = efg_terrestre.groupby("Realm (Reino)").sum("area_natural")
efg_realm_continental

                                 area_total  area_natural  porcentaje
Realm (Reino)
Freshwater                     2.265167e+06  2.167517e+06    6.813347
Freshwater-Marine              1.202678e+04  1.142688e+04    0.950120
Marine-Freshwater-Terrestrial  4.481831e+04  4.436208e+04    0.989820
Marine-Terrestrial             3.526766e+05  3.383690e+05    1.839963
Terrestrial                    6.739487e+07  5.926413e+07    9.667216
Terrestrial-Freshwater         5.733210e+06  5.705495e+06    3.156986

In [12]:
for realm, row in efg_realm_continental.iterrows():
    hectares_row = [
        indicator_code, indicator_name, is_disaggregation,
        "Realm", realm, year_indicator, "Hectares", row["area_natural"],
        hectares_footnote_continental
    ]
    percent_row = [
        indicator_code, indicator_name, is_disaggregation,
        "Realm", realm, year_indicator, "Percent", row["area_natural"] * 100 / area_continental,
        percent_footnote_continental
    ]
    indicator = pd.concat([
        indicator,
        pd.DataFrame([hectares_row, percent_row], columns=indicator_columns)
    ], ignore_index=True)
indicator

/var/folders/qk/s_6nzrrj3779504sfcscwfyr0000gn/T/ipykernel_11143/3660375567.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  indicator = pd.concat([

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Hectares,2.167517e+06,Absolute natural and semi-natural extent in th...
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Percent,2.859417e+00,Percentage relative to the total national cont...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.142688e+04,Absolute natural and semi-natural extent in th...
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.507450e-02,Percentage relative to the total national cont...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436208e+04,Absolute natural and semi-natural extent in th...
5,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Percent,5.852303e-02,Percentage relative to the total national cont...
6,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Terrestrial,2024,Hectares,3.383690e+05,Absolute natural and semi-natural extent in th...
7,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Terrestrial,2024,Percent,4.463808e-01,Percentage relative to the total national cont...
8,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Hectares,5.926413e+07,Absolute natural and semi-natural extent in th...
9,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial,2024,Percent,7.818201e+01,Percentage relative to the total national cont...
10,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Hectares,5.705495e+06,Absolute natural and semi-natural extent in th...
11,A.2,A.2 Extent of natural ecosystems,True,Realm,Terrestrial-Freshwater,2024,Percent,7.526763e+00,Percentage relative to the total national cont...

Agregar indicadores desagregados por _Ecosystem Functional Group_:

In [13]:
for idx, row in efg_terrestre.iterrows():
    efg_name = f"{row['Código EFG']} {row['group']}"
    if abs(row["area_natural"]) < 1e-6:
        print(f"Skipping {efg_name}")
    else:
        hectares_row = [
            indicator_code, indicator_name, is_disaggregation,
            "Ecosystem Functional Group", efg_name, year_indicator, "Hectares", row["area_natural"],
            hectares_footnote_continental
        ]
        percent_row = [
            indicator_code, indicator_name, is_disaggregation,
            "Ecosystem Functional Group", efg_name, year_indicator, "Percent", row["area_natural"] * 100 / area_continental,
            percent_footnote_continental
        ]
        indicator = pd.concat([
            indicator,
            pd.DataFrame([hectares_row, percent_row], columns=indicator_columns)
        ], ignore_index=True)
indicator

Skipping F3.2 Constructed lacustrine wetlands
Skipping F3.1 Large reservoirs

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Hectares,2.167517e+06,Absolute natural and semi-natural extent in th...
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Percent,2.859417e+00,Percentage relative to the total national cont...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.142688e+04,Absolute natural and semi-natural extent in th...
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.507450e-02,Percentage relative to the total national cont...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436208e+04,Absolute natural and semi-natural extent in th...
...,...,...,...,...,...,...,...,...,...
59,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,T4.5 Temperate subhumid grasslands,2024,Percent,3.062807e+00,Percentage relative to the total national cont...
60,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,T6.5 Tropical alpine grasslands and herbfields,2024,Hectares,6.711197e+06,Absolute natural and semi-natural extent in th...
61,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,T6.5 Tropical alpine grasslands and herbfields,2024,Percent,8.853499e+00,Percentage relative to the total national cont...
62,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,T1.2 Tropical/Subtropical dry forests and thic...,2024,Hectares,9.845399e+05,Absolute natural and semi-natural extent in th...
63,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,T1.2 Tropical/Subtropical dry forests and thic...,2024,Percent,1.298818e+00,Percentage relative to the total national cont...

### Flujo 2: Procesamiento Marino

#### Paso 2.1: Generación de la Capa Marina

Utilizar el polígono de la ZEE (200 millas).
Exclusión: Restar cualquier área que ya esté cubierta por el Catastro CONAF en la zona costera (ej. fiordos interiores o islas) para evitar doble contabilidad.

Ambos procesos se realizan en un script de python que elimina las intersecciones.

#### Paso 2.2: Intersección EFG Marino  (esperar capa EFG)

Cruzar el polígono de la ZEE con la capa de Grupos Funcionales Marinos de la UICN.
Esto clasificará el mar en grupos como M2 (Océano abierto pelágico), M3 (Mar profundo), etc.
> Nota: Se asume que toda la extensión de la ZEE es "Ecosistema Natural" a menos que existan capas específicas de "infraestructura marina artificial" (granjas eólicas, plataformas) que deban restarse (Clase M4/MT3). Ante la falta de datos de infraestructura marina, se contabiliza la ZEE total.

In [14]:
%%time
with engine.connect() as conn:
    efg_marino = pd.read_sql_query("""
        SELECT em."group", em.superf_ha "area_total", em.superf_ha "area_natural", em.superf_ha / em.superf_ha "porcentaje"
        FROM processed.efg_marino em;
    """, conn)
efg_marino

CPU times: user 1.58 ms, sys: 787 μs, total: 2.37 ms
Wall time: 166 ms

                                group    area_total  area_natural  porcentaje
0                      Abyssal plains  2.682246e+08  2.682246e+08         1.0
1   Coastal shrublands and grasslands  1.715466e+05  1.715466e+05         1.0
2       Continental and island slopes  4.690916e+07  4.690916e+07         1.0
3            Deepwater coastal inlets  7.361402e+06  7.361402e+06         1.0
4          Hadal trenches and troughs  3.873535e+06  3.873535e+06         1.0
5                        Kelp forests  1.198512e+07  1.198512e+07         1.0
6                    Rocky Shorelines  2.584672e+05  2.584672e+05         1.0
7                    Sandy Shorelines  4.499397e+05  4.499397e+05         1.0
8      Seamounts, ridges and plateaus  1.413342e+07  1.413342e+07         1.0
9                Subtidal rocky reefs  6.476879e+05  6.476879e+05         1.0
10                 Subtidal sand beds  2.820396e+06  2.820396e+06         1.0
11                    Upwelling zones  3.787442e+05  3.787442e+05         1.0

In [15]:
efg_code_marine = pd.read_excel("data/ajuste_a2.xlsx", sheet_name="EFG_marino", header=0)
efg_code_marine

   Código IUCN GET                   Ecosistema (EFG)               Realm
0             M3.3                     Abyssal plains              Marine
1            MT2.1  Coastal shrublands and grasslands  Marine-Terrestrial
2             M3.1      Continental and island slopes              Marine
3            FM1.2           Deepwater coastal inlets   Freshwater-Marine
4             M3.6         Hadal trenches and troughs              Marine
5             M1.2                       Kelp forests              Marine
6            MT1.1                   Rocky Shorelines  Marine-Terrestrial
7            MT1.3                   Sandy Shorelines  Marine-Terrestrial
8             M3.4     Seamounts, ridges and plateaus              Marine
9             M1.6               Subtidal rocky reefs              Marine
10            M1.4                 Subtidal sand beds              Marine
11            M2.1                    Upwelling zones              Marine

In [16]:
efg_marino = efg_marino.merge(efg_code_marine, left_on="group", right_on="Ecosistema (EFG)", how="left")
efg_marino

,group,area_total,area_natural,porcentaje,Código IUCN GET,Ecosistema (EFG),Realm
0,Abyssal plains,2.682246e+08,2.682246e+08,1.0,M3.3,Abyssal plains,Marine
1,Coastal shrublands and grasslands,1.715466e+05,1.715466e+05,1.0,MT2.1,Coastal shrublands and grasslands,Marine-Terrestrial
2,Continental and island slopes,4.690916e+07,4.690916e+07,1.0,M3.1,Continental and island slopes,Marine
3,Deepwater coastal inlets,7.361402e+06,7.361402e+06,1.0,FM1.2,Deepwater coastal inlets,Freshwater-Marine
4,Hadal trenches and troughs,3.873535e+06,3.873535e+06,1.0,M3.6,Hadal trenches and troughs,Marine
5,Kelp forests,1.198512e+07,1.198512e+07,1.0,M1.2,Kelp forests,Marine
6,Rocky Shorelines,2.584672e+05,2.584672e+05,1.0,MT1.1,Rocky Shorelines,Marine-Terrestrial
7,Sandy Shorelines,4.499397e+05,4.499397e+05,1.0,MT1.3,Sandy Shorelines,Marine-Terrestrial
8,"Seamounts, ridges and plateaus",1.413342e+07,1.413342e+07,1.0,M3.4,"Seamounts, ridges and plateaus",Marine
9,Subtidal rocky reefs,6.476879e+05,6.476879e+05,1.0,M1.6,Subtidal rocky reefs,Marine
10,Subtidal sand beds,2.820396e+06,2.820396e+06,1.0,M1.4,Subtidal sand beds,Marine
11,Upwelling zones,3.787442e+05,3.787442e+05,1.0,M2.1,Upwelling zones,Marine

In [17]:
efg_marino_total = efg_marino["area_natural"].sum()
print(f"Área natural marino: {efg_marino_total:.2f} ha")

Área natural marino: 357214024.72 ha

Agrupar por _Realm_:

In [18]:
efg_realm_marine = efg_marino.groupby("Realm").sum("area_natural")
efg_realm_marine

                      area_total  area_natural  porcentaje
Realm
Freshwater-Marine   7.361402e+06  7.361402e+06         1.0
Marine              3.489727e+08  3.489727e+08         8.0
Marine-Terrestrial  8.799535e+05  8.799535e+05         3.0

In [19]:
for realm, row in efg_realm_marine.iterrows():
    hectares_row = [
        indicator_code, indicator_name, is_disaggregation,
        "Realm", realm, year_indicator, "Hectares", row["area_natural"],
        hectares_footnote_marine
    ]
    percent_row = [
        indicator_code, indicator_name, is_disaggregation,
        "Realm", realm, year_indicator, "Percent", row["area_natural"] * 100 / efg_marino_total,
        percent_footnote_marine
    ]
    indicator = pd.concat([
        indicator,
        pd.DataFrame([hectares_row, percent_row], columns=indicator_columns)
    ], ignore_index=True)
indicator

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Hectares,2.167517e+06,Absolute natural and semi-natural extent in th...
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Percent,2.859417e+00,Percentage relative to the total national cont...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.142688e+04,Absolute natural and semi-natural extent in th...
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.507450e-02,Percentage relative to the total national cont...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436208e+04,Absolute natural and semi-natural extent in th...
...,...,...,...,...,...,...,...,...,...
65,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,2.060782e+00,Percentage relative to the total national mari...
66,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Hectares,3.489727e+08,Absolute natural and semi-natural extent in th...
67,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine,2024,Percent,9.769288e+01,Percentage relative to the total national mari...
68,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Terrestrial,2024,Hectares,8.799535e+05,Absolute natural and semi-natural extent in th...
69,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Terrestrial,2024,Percent,2.463379e-01,Percentage relative to the total national mari...

Agregar indicadores desagregados por _Ecosystem Functional Group_:

In [20]:
for idx, row in efg_marino.iterrows():
    efg_name = f"{row['Código IUCN GET']} {row['group']}"
    if abs(row["area_natural"]) < 1e-6:
        print(f"Skipping {efg_name}")
    else:
        hectares_row = [
            indicator_code, indicator_name, is_disaggregation,
            "Ecosystem Functional Group", efg_name, year_indicator, "Hectares", row["area_natural"],
            hectares_footnote_marine
        ]
        percent_row = [
            indicator_code, indicator_name, is_disaggregation,
            "Ecosystem Functional Group", efg_name, year_indicator, "Percent", row["area_natural"] * 100 / efg_marino_total,
            percent_footnote_marine
        ]
        indicator = pd.concat([
            indicator,
            pd.DataFrame([hectares_row, percent_row], columns=indicator_columns)
        ], ignore_index=True)
indicator

,Indicator code,Indicator,Does this data row represent a disaggregation,Disaggregation type,Disaggregation,Year,Unit,Value,Footnote
0,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Hectares,2.167517e+06,Absolute natural and semi-natural extent in th...
1,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater,2024,Percent,2.859417e+00,Percentage relative to the total national cont...
2,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Hectares,1.142688e+04,Absolute natural and semi-natural extent in th...
3,A.2,A.2 Extent of natural ecosystems,True,Realm,Freshwater-Marine,2024,Percent,1.507450e-02,Percentage relative to the total national cont...
4,A.2,A.2 Extent of natural ecosystems,True,Realm,Marine-Freshwater-Terrestrial,2024,Hectares,4.436208e+04,Absolute natural and semi-natural extent in th...
...,...,...,...,...,...,...,...,...,...
89,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,M1.6 Subtidal rocky reefs,2024,Percent,1.813165e-01,Percentage relative to the total national mari...
90,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,M1.4 Subtidal sand beds,2024,Hectares,2.820396e+06,Absolute natural and semi-natural extent in th...
91,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,M1.4 Subtidal sand beds,2024,Percent,7.895535e-01,Percentage relative to the total national mari...
92,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,M2.1 Upwelling zones,2024,Hectares,3.787442e+05,Absolute natural and semi-natural extent in th...
93,A.2,A.2 Extent of natural ecosystems,True,Ecosystem Functional Group,M2.1 Upwelling zones,2024,Percent,1.060273e-01,Percentage relative to the total national mari...

### Paso 3: Integración y Cálculo

Unificar los resultados del Flujo 1 y Flujo 2.
Superficie Natural Total = (Sup. Natural CONAF) + (Sup. ZEE Natural).
Superficie Total País = Sup. Terrestre Oficial + Sup. ZEE Oficial.
Calcular proporción de áreas naturales en el territorio nacional

In [21]:
area_natural_total = area_natural + efg_marino_total
print(f"Área natural total (terrestre + marino): {area_natural_total:.2f} ha")

Área natural total (terrestre + marino): 424422456.01 ha

In [22]:
indicator.to_csv("indicador_a_2.csv", header=True, index=False)