# 5.1 Proporción de las poblaciones de peces dentro de niveles biológicamente sostenibles.

In [ ]:
import datetime
now = datetime.datetime.now()
print(f"Última actualización de este notebook: {now}")

Última actualización de este notebook: 2026-03-13 12:36:23.800538

El Indicador de Cabecera 5.1 evalúa la sostenibilidad de la extracción de los recursos marinos. Su objetivo es medir el porcentaje de las poblaciones de peces (o pesquerías) sometidas a explotación comercial cuya abundancia se encuentra en niveles ecológicamente viables. De acuerdo con el glosario oficial del CBD y la FAO, se considera que una población está en un "nivel biológicamente sostenible" cuando su abundancia estimada es igual o superior al nivel necesario para producir el Rendimiento Máximo Sostenible (RMS o MSY, por sus siglas en inglés).
Los metadatos oficiales del indicador se encuentran disponibles [aquí](https://www.gbf-indicators.org/metadata/headline/5-1).

## Metodología de Cálculo

El cálculo de este indicador se basa en la evaluación del estado de situación de las principales pesquerías nacionales respecto a sus Puntos Biológicos de Referencia (PBR). Para determinar la proporción, se clasifica el estado de cada pesquería evaluada. En el sistema chileno, las pesquerías categorizadas como "Subexplotadas" o en estado de "Plena Explotación" cumplen con el estándar global de sostenibilidad (abundancia > RMS). Por el contrario, aquellas categorizadas como "Sobreexplotadas" o "Agotadas/Colapsadas" se encuentran por debajo de los umbrales biológicos seguros. El indicador final se obtiene dividiendo el número de pesquerías en estado sostenible por el total de pesquerías con PBR evaluados en el año de reporte, multiplicado por 100.

# Capa 1: Observación y recolección

## Fuentes de datos utilizadas

Los datos que sustentan este indicador son producidos oficialmente por la Subsecretaría de Pesca y Acuicultura (SUBPESCA), entidad encargada de la determinación anual del estatus de las pesquerías en Chile basándose en los informes técnicos del Instituto de Fomento Pesquero (IFOP) y los Comités Científicos Técnicos.
Para el presente reporte del 7NR, la información fue obtenida y sistematizada a partir del Reporte del Estado del Medio Ambiente 2025, publicado por el Sistema Nacional de Información Ambiental (SINIA) del Ministerio del Medio Ambiente (disponible en: https://sinia.mma.gob.cl/estado-del-medio-ambiente/reporte-del-estado-del-medio-ambiente-2025/ ). El set de datos consolidado presenta el estado de 20 especies marinas asociadas a la actividad extractiva nacional, cubriendo un total de 27 pesquerías (o unidades de pesquería) sujetas a Puntos Biológicos de Referencia.

In [1]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)

# --- Configuración ---
BASE_DIR = Path.cwd()
BASE_DIR.exists(), BASE_DIR.resolve()

(True,
 PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible'))

In [2]:
# Listar archivos esperados
csv_files = sorted(BASE_DIR.glob("*.csv"))
xlsx_files = sorted(BASE_DIR.glob("*.xlsx"))

csv_files, xlsx_files

([PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2018.csv'),
  PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2019.csv'),
  PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2020.csv'),
  PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2021.csv'),
  PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2022.csv'),
  PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2023.csv'),
  PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/2024.csv')],
 [PosixPath('/home/ricardo/Documents/IEB/BIODATA/vinculaciones/PNUD/7NR_ejecucion/7NR-Indicators/indicadores/5.1_fish_sostenible/scbd-ort-GBF-INDICATOR-5.1-data.xlsx')])

In [3]:
# Leer CSV por año (o por nombre de archivo)
dfs_csv = {}

for fp in csv_files:
    key = fp.stem  # ej: '2022'
    try:
        df = pd.read_csv(fp)
    except UnicodeDecodeError:
        # fallback común si viene en latin-1
        df = pd.read_csv(fp, encoding="latin-1")
    dfs_csv[key] = df

print("Años con datos de pesca sostenible:", list(dfs_csv.keys())[:10])

Años con datos de pesca sostenible: ['2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [5]:
# Concatenar todos los CSV (agrega columna source_file)
if dfs_csv:
    df_csv_all = (
        pd.concat(
            [df.assign(source_file=k) for k, df in dfs_csv.items()],
            ignore_index=True
        )
    )
else:
    df_csv_all = pd.DataFrame()

df_csv_all.shape

(140, 3)

# Capa 2: Análisis y síntesis

Tabla extraída y concatenada desde SINIA

In [13]:
df_csv_all.head(30)

                  Especie               Estatus source_file          Estatus_std
0                Alfonsino  Agotada o colapsada        2018  Agotada o colapsada
1                Anchoveta  Agotada o colapsada        2018  Agotada o colapsada
2   Bacalao de profundidad  Agotada o colapsada        2018  Agotada o colapsada
3                   Besugo  Agotada o colapsada        2018  Agotada o colapsada
4           Camarón Nailon    Plena explotación        2018    Plena explotación
5           Congrio dorado        Sobrexplotada        2018       Sobreexplotada
6                    Jurel       Sobreexplotada        2018       Sobreexplotada
7      Langostino Amarillo    Plena explotación        2018    Plena explotación
8      Langostino Colorado    Plena explotación        2018    Plena explotación
9            Merluza común       Sobreexplotada        2018       Sobreexplotada
10         Merluza de cola  Agotada o colapsada        2018  Agotada o colapsada
11  Merluza de tres aletas       Sobreexplotada        2018       Sobreexplotada
12         Merluza del sur       Sobreexplotada        2018       Sobreexplotada
13              Pez espada    Plena explotación        2018    Plena explotación
14           Raya volantín       Sobreexplotada        2018       Sobreexplotada
15                 Reineta       Sobreexplotada        2018       Sobreexplotada
16         Sardina austral       Sobreexplotada        2018       Sobreexplotada
17           Sardina común    Plena explotación        2018    Plena explotación
18        Sardina española  Agotada o colapsada        2018  Agotada o colapsada
19                   JIBIA    Plena explotación        2018    Plena explotación
20               Alfonsino  Agotada o colapsada        2019  Agotada o colapsada
21               Anchoveta       Sobreexplotada        2019       Sobreexplotada
22  Bacalao de profundidad       Sobreexplotada        2019       Sobreexplotada
23                  Besugo  Agotada o colapsada        2019  Agotada o colapsada
24          Camarón Nailon    Plena explotación        2019    Plena explotación
25          Congrio dorado        Sobrexplotada        2019       Sobreexplotada
26                   Jurel    Plena explotación        2019    Plena explotación
27     Langostino Amarillo    Plena explotación        2019    Plena explotación
28     Langostino Colorado        Sobrexplotada        2019       Sobreexplotada
29           Merluza común       Sobreexplotada        2019       Sobreexplotada

In [6]:
# 1) Estandarizar categorías
map_estatus = {
    "Sobrexplotada": "Sobreexplotada",
    "Subexplotación": "Subexplotada",
}

df_csv_all["Estatus_std"] = df_csv_all["Estatus"].replace(map_estatus)

# chequeo rápido: deberían quedar 5-6 categorías (según si mantienes Indeterminado)
sorted(df_csv_all["Estatus_std"].unique())

['Agotada o colapsada',
 'Indeterminado',
 'Plena explotación',
 'Sobreexplotada',
 'Subexplotada']

In [7]:
# Conteo
counts = (
    df_csv_all
    .groupby(["source_file", "Estatus_std"])
    .size()
    .reset_index(name="n_especies")
)

# Total por año (usando transform)
counts["total_especies"] = counts.groupby("source_file")["n_especies"].transform("sum")
counts["proporcion"] = counts["n_especies"] / counts["total_especies"]

prop = counts[["source_file", "Estatus_std", "proporcion"]]
prop.head()

  source_file          Estatus_std  proporcion
0        2018  Agotada o colapsada        0.30
1        2018    Plena explotación        0.30
2        2018       Sobreexplotada        0.40
3        2019  Agotada o colapsada        0.20
4        2019        Indeterminado        0.05

# Capa 3: Repporte Digital
## Resultados

De acuerdo con la evaluación oficial, de las 27 pesquerías con Puntos Biológicos de Referencia determinados en el país, aproximadamente el 40% se encuentran en un estado de explotación biológicamente sostenible (clasificadas como subexplotadas o en plena explotación). Esto significa que cerca de 11 de las 27 pesquerías monitoreadas para este indicador cumplen con los estándares de sostenibilidad global definidos por el Convenio sobre la Diversidad Biológica y la FAO. Por otro lado, alrededor del 60% de las unidades pesqueras (aproximadamente 16 pesquerías) se categorizan como sobreexplotadas o agotadas, requiriendo o manteniendo planes de recuperación, reducción de cuotas o medidas de manejo restrictivo.
El análisis de la evolución temporal del estado de las pesquerías a nivel nacional muestra una tendencia persistente a altos niveles de no sostenibilidad durante la última década. Entre 2014 y 2024, la proporción de especies o unidades pesqueras en condición no sostenible ha oscilado mayormente entre 60% y 70%, evidenciando un desafío estructural para la recuperación de las poblaciones explotadas. En contraste, la categoría de pesquerías con estado indeterminado disminuye progresivamente hasta desaparecer desde 2018, lo que sugiere un fortalecimiento del conocimiento científico y de los procesos de evaluación de stock en el país. Esta mejora en la capacidad de diagnóstico permite contar con evaluaciones más robustas para orientar las decisiones de manejo. Durante el mismo período, la proporción de pesquerías en condición sostenible ha mostrado una relativa estabilidad, fluctuando entre 30% y 40% del total evaluado. En 2014, cerca del 35% de las especies (7 de 20) se encontraban en categorías compatibles con niveles sostenibles de explotación (“Plena explotación” o “Subexplotada”). Esta proporción se mantiene en rangos similares a lo largo de la década, alcanzando aproximadamente 40% para el año 2024.

In [15]:
tabla_prop = (
    prop
    .pivot(index="source_file", columns="Estatus_std", values="proporcion")
    .fillna(0)
    .sort_index()
)

tabla_prop_fmt = tabla_prop.map(lambda x: f"{x:.1%}")
encabezado = "Distribución de Registros por Estatus y Año"

tabla_prop_fmt

Estatus_std Agotada o colapsada Indeterminado Plena explotación Sobreexplotada Subexplotada
source_file
2018                      30.0%          0.0%             30.0%          40.0%         0.0%
2019                      20.0%          5.0%             25.0%          50.0%         0.0%
2020                      25.0%          0.0%             40.0%          35.0%         0.0%
2021                      25.0%          0.0%             30.0%          40.0%         5.0%
2022                      35.0%          0.0%             30.0%          30.0%         5.0%
2023                      25.0%          0.0%             30.0%          40.0%         5.0%
2024                      30.0%          0.0%             40.0%          30.0%         0.0%

## Brechas
Una de las principales limitaciones identificadas para el cálculo y seguimiento de este indicador es la ausencia de una fuente de datos dinámica y estructurada que permita realizar consultas automatizadas sobre el estado de las pesquerías a nivel nacional. Si bien la Subsecretaría de Pesca y Acuicultura (SUBPESCA) y el Instituto de Fomento Pesquero (IFOP) generan evaluaciones periódicas del estado de las pesquerías, la información consolidada se publica principalmente a través de informes técnicos o reportes institucionales, lo que dificulta su integración directa en flujos de procesamiento automatizados para el monitoreo de indicadores. El desarrollo de infraestructuras de datos abiertos y servicios de consulta interoperables (por ejemplo, APIs o repositorios de datos estructurados) permitiría mejorar significativamente la trazabilidad, actualización y reproducibilidad del indicador. Avanzar en esta dirección facilitaría la integración de los resultados de evaluación de pesquerías en sistemas nacionales de monitoreo de biodiversidad y en futuros ciclos de reporte del Convenio sobre la Diversidad Biológica.
Actualmente, la sistematización utilizada para este reporte se basa en datos compilados en el Reporte del Estado del Medio Ambiente 2025 (SINIA), que actúa como una fuente consolidada de información. Sin embargo, este mecanismo no permite consultas programáticas ni actualizaciones automáticas del indicador a partir de los registros primarios de evaluación de pesquerías.